connection:
  host: "localhost"
  port: "8083"

mongodb:
  cluster: "astronauts.vzli9.mongodb.net"
  user: "astros"
  password: "F9wTbQ80m9cAsrmG"
  database: "astronauts"
  issdb: "iss"
  astronauts_table: "mongodb+srv://astros:F9wTbQ80m9cAsrmG@astronauts.vzli9.mongodb.net/astronauts"
  iss_table: "mongodb+srv://astros:F9wTbQ80m9cAsrmG@astronauts.vzli9.mongodb.net/astronauts"
  
astronauts-research:
  host: "http://localhost:8081/api/astronauts"
  folder:
    out: "/Volumes/Drive/AstronautsAPI/astronauts-exploration/src/main/resources/api/csv/"
  filename:
      prefix: "astronauts-research-spacedevs"
      ext: ".csv"
  
astronauts-research-iss:
  host: "http://localhost:8081/api/iss"
  folder:
    out: "/Volumes/Drive/AstronautsAPI/astronauts-exploration/src/main/resources/api/csv/"
  filename:
      prefix: "astronauts-research-iss"
      ext: ".csv"

expeditions:
  host: "http://localhost:8082/api/"
  
validation:
  collectionEmpty: "Collection of data empty, please retry!"
  contactAdmin: "An error occured! Please contact administrator!"