#%RAML 1.0
title: Astronauts Exploration API
description: AE combine information from two external API - Astronauts Research & Expeditions
  
/exploration:
  get:
    description: Retrieve data from query types
    queryParameters:
      # Use of 'data-count' is necessary in order to set the number of displayed requests
      data-count:
        required: false
      # Use of 'output-type' is necessary in order to set the type of returned data - json, file, link, html
      output-type:
        required: false
      # Use of 'help' is necessary in order to call the page using the API, two options - web page or json text
      help:
        required: false
      # Use of 'astronauts' is necessary in order for the user to get astronauts with SpaceDevs & ISS - all, spacedevs, iss
      astronauts:
        required: false
      # Use of 'iss' is needed to get the actual location of the ISS - raw, link
      iss:
        required: false
      # Use 'expedition' to get all space expeditions
      expedition:
        required: false
    responses:
      200:
        body:
          application/json:
            type: array
            examples:
              output: !include api/examples/explorationExample.raml