#%RAML 1.0 NamedExample

value:
-
  GitHub_Project: "https://github.com/merisen/astronauts-exploration-api"
  GitHub_Wiki: "https://github.com/merisen/astronauts-exploration-api/wiki"
  Authors: "Viktor Duda, Roman Skaskiv"
  Available query endpoints for /exploration:
    get_help_page: "help : info"
    display_number_of_requests: "data-count : 12"
    transform_output_format: "output-type : json, file, link, html"
    get_astronauts: "astronauts : all, spacedevs, iss"
    get_international_space_station: "iss : raw, location"
    get_astronauts_expedition: "expedition : sorted, full"