#%RAML 1.0 NamedExample

value:
-
  GitHub Project: "https://github.com/merisen/astronauts-exploration-api"
  GitHub Wiki: "https://github.com/merisen/astronauts-exploration-api/wiki"
  Authors: "Viktor Duda, Roman Skaskiv"
  Available query endpoints for /exploration:
    Get Help page: "help : info"
    Display number of requests: "data-count : 12"
    Transform output formats: "output-type : json, file, link, html"
    Get Astronauts: "astronauts : all, spacedevs, iss"
    Get International Space Station: "iss : raw, location"
    Get Astronauts Expedition: "expedition : sorted, full"